# Generated by Django 4.2.7 on 2023-11-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Minisplit', 'Minisplit'), ('Boiler', 'Boiler'), ('Ferreteria', 'Ferreteria')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
