# Generated by Django 4.2.7 on 2023-11-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name_plural': 'Ventas'},
        ),
    ]
