# Generated by Django 4.2.7 on 2023-11-17 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_order_delete_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Pedidos'},
        ),
    ]
