# Generated by Django 4.2.7 on 2023-11-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_producto_created_at_producto_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
