# Generated by Django 4.2.7 on 2023-11-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_producto_price_update_alter_producto_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
